language: node_js
node_js: stable

# S: Build Lifecycle
install:
 - npm install

#before_script:

script:
  - rm ./html/data/sites/* -rf
  - node add-all.js
  - node build.js
after_script:
  - cd ./html
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${EMAIL}"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" origin:master
# E: Build LifeCycle

branches:
  only:
    - src
