language: node_js
node_js: stable

# S: Build Lifecycle
install:
 - npm install

before_script:
  - rm ./data/sites/* -rf

script:
  - node add-all.js
after_script:
  - node build.js
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${EMAIL}"
  - git add *
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
